# Generated by Django 4.2.16 on 2024-10-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='CommunicationRequest',
        ),
    ]
